
---
dist: trusty
language: node_js
sudo: false
git:
  depth: 5

node_js: stable

cache:
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - source ~/.bashrc

stages:
  - name: Local tests
  - name: Remote tests
    if:  type IN (cron, push, pull_request) AND (fork = false) AND (tag IS blank)


jobs:
  include:
    - stage: Local tests
      script: yarn test_headless
    - stage: Remote tests
      before_script: '
        yarn run install_selenium;
        yarn run gen_capabilities_test;
      '
      script: yarn test_webdriverio
